name: PR Reporter # TODO: ci ì ìš© ì‹œ, ci ê³¼ì •ì— tc result reportingì„ í¬í•¨í•˜ê³  ì‘ì—… ì´ë¦„ì„ ë³€ê²½

on:
  pull_request:
    branches: [ develop ] # TODO: main branch PR ì‹œ ì¶”ê°€

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ€ checkout submodule
        uses: actions/checkout@v3
        with:
          submodule: true
          token: ${{secrets.PRIVATE_REPO_ACCESS_TOKEN}}

      - name: ğŸ€ debug step
        run: ls -al porko-common/src/main/resources

      - name: ğŸ€ update config submodule
        run: git submodule update --init --recursive

      - name: ğŸ€ set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: ğŸ€ grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ğŸ€ test with gradle
        run:
          ./gradlew copyProperties
          ./gradlew --info test

      - name: ğŸ€ publish unit Test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'build/test-results/**/*.xml'

      - name: ğŸ€ add comments to fail tests
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'

      - name: ğŸ€ docker build
        run: docker build -t porko-app-local .
