name: PR Reporter # TODO: ci ì ìš© ì‹œ, ci ê³¼ì •ì— tc result reportingì„ í¬í•¨í•˜ê³  ì‘ì—… ì´ë¦„ì„ ë³€ê²½

on:
  pull_request:
    branches: [ develop ] # TODO: main branch PR ì‹œ ì¶”ê°€

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ğŸ€ set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ğŸ€ grant execute permission for gradlew
        run: chmod +x gradlew

      - name: ğŸ€ test with gradle
        run: ./gradlew --info test

      - name: ğŸ€ publish unit Test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: 'build/test-results/**/*.xml'

      - name: ğŸ€ add comments to fail tests
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'build/test-results/test/TEST-*.xml'
